const {
	SlashCommandBuilder,
	EmbedBuilder,
	ButtonBuilder,
	ButtonStyle,
	ActionRowBuilder,
	ComponentType,
	AttachmentBuilder,
} = require('discord.js');
const { Types } = require('mongoose');
const { createSubmission } = require('../../tcgHelper/manageSubmissions');
const Profile = require('../../schemas/profileSchema');
const CardSubmission = require('../../schemas/cardSubmissionSchema');

module.exports = {
	data: new SlashCommandBuilder()
		.setName('submit')
		.setDescription('Submit a card, border, or general ')
		.addAttachmentOption(option =>
			option
				.setName('artwork')
				.setDescription('Artwork to use for the card')
				.setRequired(true)),
	async execute(interaction, client) {
		await interaction.deferReply({ ephemeral: true });
		const artwork = interaction.options.getAttachment('artwork');

		// Send error message if the file is not a png or jpg

		// Get the player's profile
		const player = await client.getProfile(interaction);
		if (!player) return;

		// Create new card submission object
		const cardSubmission = await new CardSubmission({
			_id: Types.ObjectId(),
		});

		// Start the submission process
		await acceptTOSCollector(player, interaction, client, cardSubmission, artwork);
	},
};

async function acceptTOSCollector(player, interaction, client, cardSubmission, artwork) {
	// If the player has already accepted the TOS, skip this step
	if (player.acceptedTOS) return await createArtistProfile(player, interaction, client, cardSubmission, artwork);

	// Create TOS Embed
	const tosEmbed = new EmbedBuilder()
		.setColor(0x0099FF)
		.setTitle('Please accept the TOS before continuing')
		.setDescription(
			`Thank you <@${interaction.user.id}> for submitting your artwork to Pentaguards! 🔥

                Before we can continue creating your card, please read the following:
                
                📜 Terms and conditions:
                - Your submission is AI artwork and generated by you (don't submit AI artwork made by someone else)
                - The AI artwork's content is suitable for ages 13 and older (no NSFW or disturbing content)
                
                Breaking the terms and conditions may result in a removal of your Card from the database, timeout or ban from the Pentaguards Discord server.
                
                📄 Process and notes:
                - You are asked to fill out information about your Card
                - You can choose how to be credited (social media link, Discord username or not to be credited)
                - Your AI artwork will be automatically cropped to 2x3 aspect ratio from the middle
                - Your AI artwork will receive a border artwork based on the information you've given
                - You are assigned with a randomized identification artist ID (your future Card uploads will use this same ID)
                - Your submission will be forwarded to approval
                - You will receive a confirmation DM when your Card is approved or denied
                
                ✅ After approval:
                - Your Card will be added to the database and released to the community in a future Card batch release
                - Pentaguards can use your AI artwork in Cards and promotional materials
                - Pentaguards can add, modify or remove your Card's information in future game design changes
                
                To proceed with your AI artwork submission, you must "Agree" or "Disagree" to the contents of this message.`);

	// Create TOS buttons
	const tosAccept = new ButtonBuilder()
		.setCustomId('tosAccept')
		.setLabel('Accept')
		.setStyle(ButtonStyle.Primary);

	const tosReject = new ButtonBuilder()
		.setCustomId('tosReject')
		.setLabel('Reject')
		.setStyle(ButtonStyle.Danger);

	const tosButtons = new ActionRowBuilder().addComponents(tosAccept, tosReject);

	// Send the TOS embed with the buttons
	const currPage = await interaction.editReply({
		embeds: [tosEmbed.setFooter({ text: `Part 1 / 5` })],
		components: [tosButtons],
		fetchReply: true,
	});

	// Create a message collector
	const tosCollector = await currPage.createMessageComponentCollector({
		componentType: ComponentType.Button,
		max: 1,
	});

	// Send next message if user accepts TOS. Cancel submission process if they reject.
	tosCollector.on('collect', async (i) => {
		await i.deferUpdate();
		await tosCollector.stop();
		switch (i.customId) {
		case 'tosAccept':
			// Set TOS accepted state to true
			await Profile.updateOne({ id: interaction.user.id }, { acceptedTOS: true });

			// Continue to the next page
			await createArtistProfile(player, interaction, client, cardSubmission, artwork);
			break;
		case 'tosReject':
			const rejectEmbed = new EmbedBuilder()
				.setColor(0xFF0000)
				.setDescription('Submission canceled.');
			await interaction.editReply({
				embeds: [rejectEmbed],
				components: [],
			});
		}
	});
}

async function createArtistProfile(player, interaction, client, cardSubmission, artwork) {
	// Call function to set up artist profile if it is not set up yet.
	const artistProfile = await client.getDiscordArtist(interaction);
	if (!artistProfile) {
		const artistProfileEmbed = new EmbedBuilder()
			.setColor(0x0099FF)
			.setTitle('Please Create Your Artist Profile')
			.setDescription(`
            You do not have an artist profile yet.
            Please click the button below to fill out your profile.
            `)
			.setFooter({ text: `Part 1a / 5` });

		const createArtistProfileButton = new ButtonBuilder()
			.setCustomId('createArtistProfileButton')
			.setLabel('Create Artist Profile')
			.setStyle(ButtonStyle.Secondary);

		const row = new ActionRowBuilder().addComponents(createArtistProfileButton);

		const currPage = await interaction.editReply({
			embeds: [artistProfileEmbed],
			components: [row],
		});

		// Create a message collector
		const artistCollector = await currPage.createMessageComponentCollector({
			componentType: ComponentType.Button,
			max: 1,
		});

		artistCollector.on('end', async () => {
			// Continue to the next page
			await createThemeCollector(player, interaction, cardSubmission, artwork);
		});
	}
	else {
		// Continue to the next page
		await createThemeCollector(player, interaction, cardSubmission, artwork);
	}
}

async function createThemeCollector(player, interaction, cardSubmission, artwork) {
	// Create Theme Embed
	const themeEmbed = new EmbedBuilder()
		.setColor(0x0099FF)
		.setTitle('Please Choose a Theme')
		.setDescription(
			`Please choose a Theme (time period) for your AI artwork:

            🐲 Fantasai | Fantasy = the faculty or activity of imagining impossible or improbable things
            - Magic, gravity breaking landscapes (floating islands, levitating rock pillars)
            - The aesthetic of middle ages lifestyle, castle, a knight in armor, character in elaborate attire...
            
            🌍 Modernai | Modern = "relating to the present or recent times as opposed to the remote past
            - Grounded by our reality: familiar landscapes, people, animals, everyday foods and transport...
            - Shares similarities with fantasy (middle ages) and future (technology & product design)
            
            🚀 Futurai | Future = a period of time following the moment of speaking or writing; time regarded as still to come
            - Anything high technology and space related, lightsabers, floating cities, aliens, what lurks in the universe
            - The aesthetic (sleek car design, planet landscape)`);

	// Create Theme buttons
	const fantasai = new ButtonBuilder()
		.setCustomId('fantasai')
		.setLabel('Fantasai')
		.setEmoji('🐲')
		.setStyle(ButtonStyle.Secondary);

	const modernai = new ButtonBuilder()
		.setCustomId('modernai')
		.setLabel('Modernai')
		.setEmoji('🌍')
		.setStyle(ButtonStyle.Secondary);

	const futurai = new ButtonBuilder()
		.setCustomId('futurai')
		.setLabel('Futurai')
		.setEmoji('🚀')
		.setStyle(ButtonStyle.Secondary);

	const cancelSubmission = new ButtonBuilder()
		.setCustomId('cancelSubmission')
		.setLabel('Cancal Submission')
		.setStyle(ButtonStyle.Danger);

	const themeButtons = new ActionRowBuilder().addComponents(fantasai, modernai, futurai, cancelSubmission);

	// Send the Theme embed with the buttons
	const currPage = await interaction.editReply({
		embeds: [themeEmbed.setFooter({ text: `Part 2 / 5` })],
		components: [themeButtons],
		fetchReply: true,
	});

	// Create a message collector
	const themeCollector = await currPage.createMessageComponentCollector({
		componentType: ComponentType.Button,
		max: 1,
	});

	// Collect user input and proceed to the next page
	themeCollector.on('collect', async (i) => {
		await i.deferUpdate();
		await themeCollector.stop();
		switch (i.customId) {
		case 'cancelSubmission':
			const rejectEmbed = new EmbedBuilder()
				.setColor(0xFF0000)
				.setDescription('Submission canceled.');
			return await interaction.editReply({
				embeds: [rejectEmbed],
				components: [],
			});
		case 'fantasai':
			cardSubmission.theme = '🐲 Fantasai';
			break;
		case 'modernai':
			cardSubmission.theme = '🌍 Modernai';
			break;
		case 'futurai':
			cardSubmission.theme = '🚀 Futurai';
			break;
		default:
			throw console.error;
		}

		await createCategoryCollector(player, interaction, cardSubmission, artwork);
	});
}

async function createCategoryCollector(player, interaction, cardSubmission, artwork) {
	// Create Category Embed
	const categoryEmbed = new EmbedBuilder()
		.setColor(0x0099FF)
		.setTitle('Please Choose a Category')
		.setDescription(
			`<@${interaction.user.id}> has selected ${cardSubmission.theme}!
            We now have the Theme selected for your Card!
            
            Next, please choose the Category for your AI artwork:

            🧍Character
            - People, portraits, aliens, demihumans, gods...
            
            🦙 Creature
            - Animals, monsters, dragon...
            
            🌄 Scape
            - Mood, nature, landscapes, buildings, interior designs, space, galaxies, botanical, foliage...
            
            🛠️ Equipment
            - Weapons, guns,wearable, clothing, accessories, throwable, transport, vehicles, magic...
            
            🍎 Consumable
            - Foods, drinks, potions, elixir, snacks, buffs...
            
            🔘  Extres
            - Abstract, religion, currency, technology, misc...`);

	// Create Category buttons
	const character = new ButtonBuilder()
		.setCustomId('character')
		.setLabel('Character')
		.setEmoji('🧍')
		.setStyle(ButtonStyle.Secondary);

	const creature = new ButtonBuilder()
		.setCustomId('creature')
		.setLabel('Creature')
		.setEmoji('🦙')
		.setStyle(ButtonStyle.Secondary);

	const scape = new ButtonBuilder()
		.setCustomId('scape')
		.setLabel('Scape')
		.setEmoji('🌄')
		.setStyle(ButtonStyle.Secondary);

	const equipment = new ButtonBuilder()
		.setCustomId('equipment')
		.setLabel('Equipment')
		.setEmoji('🛠️')
		.setStyle(ButtonStyle.Secondary);

	const consumable = new ButtonBuilder()
		.setCustomId('consumable')
		.setLabel('Consumable')
		.setEmoji('🍎')
		.setStyle(ButtonStyle.Secondary);

	const extres = new ButtonBuilder()
		.setCustomId('extres')
		.setLabel('Extres')
		.setEmoji('🔘')
		.setStyle(ButtonStyle.Secondary);

	const cancelSubmission = new ButtonBuilder()
		.setCustomId('cancelSubmission')
		.setLabel('Cancel Submission')
		.setStyle(ButtonStyle.Danger);

	const categoryButtons1 = new ActionRowBuilder().addComponents(character, creature, scape, cancelSubmission);
	const categoryButtons2 = new ActionRowBuilder().addComponents(equipment, consumable, extres);

	// Send the Category embed with the buttons
	const currPage = await interaction.editReply({
		embeds: [categoryEmbed.setFooter({ text: `Page 3 / 5` })],
		components: [categoryButtons1, categoryButtons2],
		fetchReply: true,
	});

	// Create a message collector
	const categoryCollector = await currPage.createMessageComponentCollector({
		componentType: ComponentType.Button,
		max: 1,
	});

	// Collect user's choice for category
	categoryCollector.on('collect', async (i) => {
		await i.deferUpdate();
		await categoryCollector.stop();
		switch (i.customId) {
		case 'cancelSubmission':
			const rejectEmbed = new EmbedBuilder()
				.setColor(0xFF0000)
				.setDescription('Submission canceled.');
			return await interaction.editReply({
				embeds: [rejectEmbed],
				components: [],
			});
		case 'character':
			cardSubmission.category = '🧍 Character';
			break;
		case 'creature':
			cardSubmission.category = '🦙 Creatures';
			break;
		case 'scape':
			cardSubmission.category = '🌄 Scape';
			break;
		case 'equipment':
			cardSubmission.category = '🛠️Equipment';
			break;
		case 'consumable':
			cardSubmission.category = '🍎 Consumable';
			break;
		case 'extres':
			cardSubmission.category = '🔘 Extres';
			break;
		default:
			throw console.error;
		}

		categoryCollector.stop();
		await createStyleCollector(player, interaction, cardSubmission, artwork);
	});
}

async function createStyleCollector(player, interaction, cardSubmission, artwork) {
	// Create Style Embed
	const styleEmbed = new EmbedBuilder()
		.setColor(0x0099FF)
		.setTitle('Please Choose a Style')
		.setDescription(
			`<@${interaction.user.id}> has selected ${cardSubmission.category}, in ${cardSubmission.theme}!

            Next, what's the Style of your AI artwork:
            
            🌸 Anime
            
            📷 Realistic
            - Photorealism, hyperrealism, photograph
            
            🖌️ Stylized
            - Digital painting, concept art, oil painting, watercolor`);

	// Create Style buttons
	const anime = new ButtonBuilder()
		.setCustomId('anime')
		.setLabel('Anime')
		.setEmoji('🌸')
		.setStyle(ButtonStyle.Secondary);

	const realistic = new ButtonBuilder()
		.setCustomId('realistic')
		.setLabel('Realistic')
		.setEmoji('📷')
		.setStyle(ButtonStyle.Secondary);

	const stylized = new ButtonBuilder()
		.setCustomId('stylized')
		.setLabel('Stylized')
		.setEmoji('🖌️')
		.setStyle(ButtonStyle.Secondary);

	const cancelSubmission = new ButtonBuilder()
		.setCustomId('cancelSubmission')
		.setLabel('Cancel Submission')
		.setStyle(ButtonStyle.Danger);

	const styleButtons = new ActionRowBuilder().addComponents(anime, realistic, stylized, cancelSubmission);

	// Send the Style embed with the buttons
	const currPage = await interaction.editReply({
		embeds: [styleEmbed.setFooter({ text: `Page 4 / 5` })],
		components: [styleButtons],
		fetchReply: true,
	});

	// Create a message collector
	const styleCollector = await currPage.createMessageComponentCollector({
		componentType: ComponentType.Button,
		max: 1,
	});

	// Collect user's choice for category
	styleCollector.on('collect', async (i) => {
		await i.deferUpdate();
		await styleCollector.stop();
		switch (i.customId) {
		case 'cancelSubmission':
			const rejectEmbed = new EmbedBuilder()
				.setColor(0xFF0000)
				.setDescription('Submission canceled.');
			return await interaction.editReply({
				embeds: [rejectEmbed],
				components: [],
			});
		case 'anime':
			cardSubmission.style = '🌸 Anime';
			break;
		case 'realistic':
			cardSubmission.style = '📷 Realistic';
			break;
		case 'stylized':
			cardSubmission.style = '🖌 Stylized';
			break;
		default:
			throw console.error;
		}

		await additionalInfo(player, interaction, cardSubmission, artwork);
	});
}

async function additionalInfo(player, interaction, cardSubmission, artwork) {
	const additionalInfoEmbed = new EmbedBuilder()
		.setColor(0x0099FF)
		.setTitle('Fill out additional card information')
		.setDescription(`
            - Card Name
            - AI Model
            `)
		.setFooter({ text: `Part 5 / 5` });

	const additionalCardInfo = new ButtonBuilder()
		.setCustomId('additionalCardSubmissionInfoButton')
		.setLabel('Fill Out Additional Card Info')
		.setStyle(ButtonStyle.Secondary);

	const row = new ActionRowBuilder().addComponents(additionalCardInfo);

	await interaction.editReply({
		embeds: [additionalInfoEmbed],
		components: [row],
	});

	// Source: https://stackoverflow.com/questions/72792015/modal-collector-discord-js
	// Get the Modal Submit Interaction that is emitted once the User submits the Modal
	const submitted = await interaction.awaitModalSubmit({
		time: 60000,
		// Make sure we only accept Modals from the User who sent the original Interaction we're responding to
		filter: i => i.user.id === interaction.user.id,
	}).catch(error => {
		// Catch any Errors that are thrown
		console.error(error);
		return null;
	});

	// Process the modal input and proceed to the final page
	if (submitted) {
		cardSubmission.name = submitted.fields.getTextInputValue('cardName');
		cardSubmission.aiModel = submitted.fields.getTextInputValue('aiModel');
		await submitted.update('');
		await finalPage(player, interaction, cardSubmission, artwork);
	}
}

async function finalPage(player, interaction, cardSubmission, artwork) {
	// Generate the card image
	const submissionID = await createSubmission(cardSubmission.theme.substring(3), cardSubmission.category.substring(3), artwork.attachment);
	cardSubmission.id = submissionID;
	cardSubmission.webp = `https://pentaguards.phanturne.workers.dev/submissions/webp/${submissionID}.webp`;
	cardSubmission.png = `https://pentaguards.phanturne.workers.dev/submissions/png/${submissionID}.png`;
	cardSubmission.jpg = `https://pentaguards.phanturne.workers.dev/submissions/jpg/${submissionID}.jpg`;
	cardSubmission.status = 'Pending';

	// Show user their submitted card
	const submissionEmbed = new EmbedBuilder()
		.setColor(0x0099FF)
		.setTitle('Your Card Submission')
		.setDescription(`<@${interaction.user.id}>, you have successfully submitted a card! The community will vote on it after it has been approved.`)
		.setImage(cardSubmission.webp)
	await interaction.editReply({
		embeds: [submissionEmbed],
		components: [],
	});

	// @TODO: Save the card submission to the submission database and add it to the artist's submissions
	await cardSubmission.save().catch(console.error);
}